### ISSUE TITLE
Teachers DB out of date?

### ISSUE THREAD

**Issue by ewoudenberg** [dharmaseed/dharmaseed-android#89] opened 2023-10-23 18:34 UTC
Hi @intermarc, @bb4242 and @jakewilson,

First of all, thank you for your recent contributions to the Android app! It is lovely to see the interest and energy you are putting toward improving the app and keeping it running well.

Eric M (@ericm108) and I wanted to point out a few small items we noticed that seem related to the teacher db possibly getting out of date:

- There are teachers that have pictures on the website that are not showing up on the app (e.g. Ajahn Sundara, Brad Richecoeur, David Loy ...). When teacher info on the website is updated, we update the "update_date" field in our DB and so the api will present these teachers anew in the items list. However, e.g. Ajahn Sundara's photo and bio were added Nov 18 2022, though they don't appear under her entry in the app.
- Tara Mulay is not in the app's teacher list, but her talks show up properly in the app's "centers" listing. See e.g. Insight Meditation Society - Retreat Center.
- Related: There are teacher entries that no longer exist (e.g. "Steve Armstrong & Kamala Masters", "Kittisaro & Thanissara" -- those are now properly handled as multiple teachers on a single talk), but the app still shows the combined entry for them. Our removal of that entry would have caused the entry to appear in the x_items list under teachers.
- Our DB and the API now support multiple teachers on a single talk. The "teacher" field in the API remains and that now contains the "primary" teacher that sets permissions for a talk's availability on the website. The new "teachers" field in the API is a list of all the teachers that are included in the talk.

Much of this may boil down to whether x_items is being properly handled for teachers.

We thank you again for your diligence and effort! It is wonderful to have this app available for Android users.

Kind regards,
Eric W and Eric M

**Comment by bb4242** [comment] 2023-10-24 23:03
Hi @ewoudenberg and @ericm108! So nice to connect with you, hope you're both doing well. Thanks very much for this detailed report. I especially appreciate that you included specific examples of teachers that aren't showing up properly, etc. Those will be very helpful during testing to make sure that we've properly solved the problem. Thanks also for pointing out some of the new features of the API like the support for multiple teachers on a talk. That's great to know that you're continuing to evolve things on your end too, and of course we're happy to update the app to stay in sync with those changes. :smile: 

It's my intention to fix the issues that you've raised quickly - I think they're important! At the moment, I'm trying to track down the cause of some relatively rare and hard to reproduce crashes that have surfaced in production after we released #87. Haha it's turned into a larger rabbit hole than I anticipated. It seems that there may be some bugs in the underlying Android media framework we've switched to that are affecting many other apps as well (if anyone is curious, see [this bug](https://github.com/androidx/media/issues/167) with its hundreds of comments for context :wink:). In any case, I'm hoping to find a good fix for that soon, after which point I'm more than happy to start working on the DB issues.

In the meantime, @intermarc or @jakewilson, if you feel any inclination toward working on the DB now or in the future, please feel free to dive in anywhere that seems interesting to you. But of course no pressure or expectation; @jakewilson I recall you mentioned that you switched to using an iPhone recently so I'm not sure if continuing to do Android development is on your radar. :smile: And @intermarc I know you mentioned you might be interested in developing a talk history feature in the app, so if that's still of interest please don't feel like you need to switch your focus to DB stuff. If anyone does decide to jump into any DB stuff, please just make a comment here describing what you're working on so we can coordinate our efforts, and I'll do the same.

Thanks everyone, I'm happy to be working on this with you all. Best wishes.

**Comment by intermarc** [comment] 2023-11-04 22:02
Thanks for the great bug report! As @bb4242 pointed out, it's really super helpful to have such concrete examples provided.

I had my first look at the DB synchronization code in the app today and it looks really solid to me. The issue is probably not connected to the handling of the `x_items` list, in my opinion, as the exact same code handles all tables (teachers, talks, centers). Unless the deletion of items is entirely broken for all tables, the problem must lie elsewhere.

I came across a different potential explanation for the DB divergence that appears to have taken place, though, and thought I would post it here to see what you think. The issue might be related to the errors that occur upon concurrent access to the sqlite DB in the app, similar to what was reported [here](https://stackoverflow.com/questions/2647542/android-threading-and-database-locking).

Apparently, the locking mechanisms in `SQLiteDatabase` changed with API level 16. According to one answer in [this post](https://stackoverflow.com/questions/6675240/is-sqlite-database-instance-thread-safe), `SQLiteDatabase` objects no longer provide a locking mechanism to guard against concurrent access (see the answer by Adam Burley).

Here is what I think might be going on:

1. Our DB tables are updated asynchronously and concurrently using `AsyncTask` objects created in [org.dharmaseed.android.NavigationActivity#fetchNewDataFromServer](https://github.com/dharmaseed/dharmaseed-android/blob/0d1b249390727828eee3be67d120d85e3a798731/app/src/main/java/org/dharmaseed/android/NavigationActivity.java#L365)
2. If several tables are updated during the same refresh, we might end up with concurrent calls to [org.dharmaseed.android.DBManager#insertItem](https://github.com/dharmaseed/dharmaseed-android/blob/0d1b249390727828eee3be67d120d85e3a798731/app/src/main/java/org/dharmaseed/android/DBManager.java#L174) from [org.dharmaseed.android.DataFetcherTask#updateTable](https://github.com/dharmaseed/dharmaseed-android/blob/0d1b249390727828eee3be67d120d85e3a798731/app/src/main/java/org/dharmaseed/android/DataFetcherTask.java#L60)
3. `org.dharmaseed.android.DBManager#insertItem` includes a generic `catch (Exception e)` that would basically swallow any concurrent DB access exceptions.
4. The editions table is updated (despite the exceptions, which have been caught) near the end of `org.dharmaseed.android.DataFetcherTask#updateTable` and the affected DB insertions are lost for ever, since any subsequent refresh will trigger an update with respect to the last entry in the editions table.
 
The issue with the teacher's photos could be a consequence of this. Updates to the teachers table are lost and the App never registers that a picture is available. This is what appears to have happened in the case of Ajahn Sundara: the teacher table in the app indicates that no photo is available (`photo.equals("")` in [org.dharmaseed.android.TeacherFetcherTask#doInBackground](https://github.com/dharmaseed/dharmaseed-android/blob/0d1b249390727828eee3be67d120d85e3a798731/app/src/main/java/org/dharmaseed/android/TeacherFetcherTask.java#L47) ).

If this is indeed the issue, it should not be too difficult to fix by including appropriate semaphores in the DB update routines of `DBManager`. It might also be a good idea to remove `catch (Exception e)`-like code from the synchronization process, such that the editions table is not updated unless all of the changes to the DB were successful.

The other question is how to deal with the diverged DBs on users' phones. Fixing the code will not fix those, unfortunately.

Let me know what you think @bb4242 and/or @jakewilson. I'm happy to work on implementing any changes required to fix this issue. Perhaps it would be best to try to reproduce the issue first, though.

**Comment by ewoudenberg** [comment] 2023-11-04 22:46
Hi @intermarc ,

Your analysis sounds good (though I have not looked at the code). Your solution of guarding against concurrent DB access with semaphores seems sensible. One cheaper and dirtier solution would be to simply not update the edition information if the DB update fails for any reason. Presumably the DB update would be tried again reasonably quickly (or on app start).

I wanted to mention that every version of the iPhone app is built with the latest DB installed in it so that updates that occur each time the app starts require little to be downloaded, at least for a while. I don't know if the Android app is built in this way, but if so, then at least users will have their DB integrity restored when they get the latest version of the app.

Thank you kindly for looking into this and for your work on the app!

Eric W.

**Comment by intermarc** [comment] 2023-11-05 16:11
Those are good suggestions, @ewoudenberg. Thank you! I'm currently working on some patches to address the issue and they do take the approaches you describe.

In the tests I was running today I wasn't able to reproduce any concurrency related issues during DB synchronization. This kind of problem does not seem to crop up often (if at all?), such that it does not warrant much effort. Moving the exception handling further up the stack is a simple fix, as you suggest.

My tests did, however, reveal what must be the real culprit here: the app was simply not updating existing items due to the `if(keyExists(ID))` filter in [org.dharmaseed.android.DataFetcherTask.RequestAggregator#addID](https://github.com/dharmaseed/dharmaseed-android/blob/4dfbde1702a1d1065241448e5fcecf6dcbc1214e/app/src/main/java/org/dharmaseed/android/DataFetcherTask.java#L189)! This explains why entries and photos such as those of Ajahn Sundara were not being updated.

To fix the divergent DBs of existing users, the patches will include functionality to perform DB updates when a new version of the app is installed (similar to what happens in the iPhone app). Hopefully I will have a pull request ready soon.

**Comment by bb4242** [comment] 2023-11-05 21:30
Hi @intermarc. Thank you kindly for digging into this, I'm grateful for your help! The analysis you've described sounds correct to me, and from reading the thoughtful description you wrote up in #90, I think you've taken a really sensible approach. I'm intending to take a closer look at your PR this week (haha and reacquaint myself with the DB synchronization code in the process). In the meantime I just wanted to thank you again for your contributions. :slightly_smiling_face:

**Comment by bb4242** [comment] 2023-11-29 23:41
@intermarc's database fixes, #90 and #93, are now publicly released. :tada:  According to our testing, this should address the first 3 bullet points/failure cases that @ewoudenberg mentioned in the initial report for this issue, and more generally, ensure that the database remains properly synchronized going forward. Thanks @ewoudenberg for the report and @intermarc for the fix!

Regarding the fourth bullet point, I'm planning on adding support for the new "teachers" field in the API soon, so that we'll display all teachers associated with the talk in the talk detail activity. I'll leave this issue open until we address that piece also, but just wanted to convey that the parts of this issue related to the database synchronization should be fixed now. If anyone notices any further database problems going forward, please let us know!

**Closed** 2023-12-23 08:49 UTC

**Comment by bb4242** [comment] 2023-12-29 21:06
Just a quick note to say that the support for multiple teachers per talk (#95) is now released to production (in version 1.6.0).
